### PR TITLE
Add metrics on contributors page

### LINKED ISSUE #136: Show leaderboard metrics in contributor profile too
The weekly metrics shown in the leaderboard could be shown on the contributor's profile page too

image

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #136 
image

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
1. Fix the eslint/prettier errors

2. Not a fan of this UI, could we do something better? This would confuse the user on which is past weeks data and which is global data.

**Comment by rithviknishad** [comment]
@Pranshu1902 also rebase with latest main.

**Comment by Pranshu1902** [comment]
Updated view @rithviknishad 
image

**Review by rithviknishad — APPROVED** [review]
Awesome! LGTM

**Pull request merged**
