### PR TITLE
Added indentation at left of text in "Currently Working on" tab

### LINKED ISSUE #85: Minor UI fix for "Currently Working on" tab
Add extra spacing for text at left in mobile view
image

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #85 
Added spacing for mobile view
image

### CODE REVIEW

**Comment by khavinshankar** [comment]
@Pranshu1902 merge conflicts

**Comment by Pranshu1902** [comment]
@khavinshankar resolved!

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@Pranshu1902 now it looks like this

image

**Comment by Pranshu1902** [comment]
Updated view:
image

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
