### PR TITLE
Remove existing bots from github scrapper

### PR DESCRIPTION
**Pull request by rabilrbl**
Removes `snyk-bot` and `vercel[bot]`

### CODE REVIEW

**Comment by bodhish** [comment]
It should also include github bot right😅

**Comment by rabilrbl** [comment]
@bodhish I only tried to add bots that were in `/data/github`. Adding GitHub bot

**Comment by bodhish** [comment]
@rabilrbl can you fix the merge conflicts

**Comment by rabilrbl** [comment]
@bodhish merged and fixed

**Pull request merged**
