### PR TITLE
Fix side effects caused by searchTerm

### LINKED ISSUE #75: Critical Bug in search
- As I type my name, I hold the "1" badge
- Under all categories in "Top Contributors of the week" my name appear.
image

### PR DESCRIPTION
**Pull request by Ritesh-Aggarwal**
closes #75 & #76

### CODE REVIEW

**Comment by Ritesh-Aggarwal** [comment]
image

**Comment by rithviknishad** [comment]
Closes #78

**Comment by rithviknishad** [comment]
Fixes #78

**Comment by Ashesh3** [comment]
+1

**Comment by gigincg** [comment]
Nice work @Ritesh-Aggarwal

**Pull request merged**
