### PR TITLE
Refactor: made /leaderboard fully SSR

### PR DESCRIPTION
**Pull request by Re-Dei**
## Issue Fixed:
#247 

## Changes:
- Lazy loaded profile pictures in /leaderboard route
- Separated searchbar from Leaderboard component
- Search occurs only on form submit i.e. on pressing enter
- Made Leaderboard component fully SSR
- Made a wrapper on Leaderboard component to get data from the function asynchronously so that the page renders before getting data
- Moved search bar to page.tsx

## Problem Solved:
The /leaderboard route should load faster.

## Testing:
Ran development in WSL2 successfully. Yet to be checked on production environment

### CODE REVIEW

**Comment by Re-Dei** [comment]
Could you recommend me any changes that reduces the number of merge conflicts?

**Comment by Re-Dei** [comment]
Thats weird it ran without an issue on development. Is there any more error logs associated with it? @rithviknishad

**Comment by Re-Dei** [comment]
@rithviknishad please try deploying again. The new commit should have fixed the previous issue.

**Comment by rithviknishad** [comment]
> Thats weird it ran without an issue on development. Is there any more error logs associated with it? @rithviknishad

`pnpm dev` runs a development server so pre-rendering does not happen there.

`pnpm build` does pre-render pages at build time and those can be previewed using `pnpm start`

**Comment by Re-Dei** [comment]
Do I need to do anything to handle the merge conflict or will the maintainers handle it?

**Comment by rithviknishad** [comment]
> Do I need to do anything to handle the merge conflict or will the maintainers handle it?

Yup, you can resolve the conflicts now. Let's get this merged ASAP once resolved

**Comment by Re-Dei** [comment]
@rithviknishad I will be merging the latest main branch to this branch right now.

**Comment by Re-Dei** [comment]
@rithviknishad please review this

**Comment by rithviknishad** [comment]
@Re-Dei there are some changes in the responsiveness and layouts in your PR which might be unintentional...

### Before (filters)

image

### After (filters)

image


### Before (Top contributors of the Week)

image

### After (Top contributors of the Week)

image

**Comment by rithviknishad** [comment]
> @rithviknishad please review this. Also, I recommend creating a separate file for constants in root directory since importing a constant from a client component to server component could cause an error while compiling a server component because the constant is unaccessible to the server component since the constant is in the uncompiled client component. I hope my explanation is understandable. If it is not, then sorry since I am not that great in explaining.
> 
> Edit: making a separate file for constant in server will make that file available for server component.

Makes sense @Re-Dei, that's a good idea. File a separate issue for it!

**Comment by Re-Dei** [comment]
@rithviknishad I did not find any difference in the after(filter) image and the layout in the previous push. The top contributors has been fixed.
Screenshot (46)
Is this intentional? When someone is searched the top contributors update based on that result.

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
