### PR TITLE
Added hyperlink for comments, and changed from using Link to anchor tag

### PR DESCRIPTION
**Pull request by UdaySagar-Git**
Fixes - #377 

- Changed from using Link to anchor tags , since those are not used for client side navigation and are external links, and would be better if they open in new tab by default  

image

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Nice work... Can we also comment look like a comment by adding a border around it and improving the UI?

Currently this does not look/feel like a comment

**Comment by UdaySagar-Git** [comment]
@rithviknishad sure

**Comment by UdaySagar-Git** [comment]
@rithviknishad does this look fine?
image

**Comment by rithviknishad** [comment]
Yup, maybe we can add a bit more padding in desktop view and reduce the font size a bit.

**Comment by UdaySagar-Git** [comment]
@rithviknishad 
I think we need to add that to all type of events ?
what do you think ? is it ok to change ui only for comments
image

**Comment by rithviknishad** [comment]
Yea, but for pull requests open/merge, or issue open/close, review approvals without comments, we should be using the OpenGraphImage. Rest of the comment events can be done like as you've mentioned

**Comment by UdaySagar-Git** [comment]
@rithviknishad 
image

Should i add the styles for issue opened /closed ??

**Comment by rithviknishad** [comment]
@UdaySagar-Git why are we changing those?

We should ideally be showing `<OpenGraphImage />` for those instead like how we have in feed.
Was it not the case already?

image

**Comment by UdaySagar-Git** [comment]
@rithviknishad we are not showing OpenGraphImage  earlier , 
i will change that to use openGraphImage

**Comment by UdaySagar-Git** [comment]
@rithviknishad can you please review now !

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
