### PR TITLE
fix theme for footer

### LINKED ISSUE #411: Footer doesn't respect the theme.
1. the logo does't show up
2. The light mode switch is not respected

image

### PR DESCRIPTION
**Pull request by rash-27**
- closes #411 
- also fixed the footer at bottom
- after changes 
image

### CODE REVIEW

**Comment by rash-27** [comment]
@rithviknishad, Is the colour for the footer in the light theme ok?

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Can we switch to using light secondary/gray color?
As for the visibility of the logo in light colors, we can apply invert and brightness tailwind classes to make the logo look black.

**Comment by rash-27** [comment]
Yeah sure, ill update it

**Comment by rash-27** [comment]
image
is this ok?
and also logo cant always be a color image right ?

**Comment by rithviknishad** [comment]
Ideally we could have two files: `logo-light.webp` and `logo-dark.webp`. This looks fine for now

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
