### PR TITLE
change cron time to every 12 hours

### LINKED ISSUE #57: Changing cron time to 7:00 PM
For checking the progress of the students for the entire day we can update the data at 7:00 PM just before EOD rather than in the morning.

### PR DESCRIPTION
**Pull request by kunatastic**
fixes #57

### CODE REVIEW

**Comment by bodhish** [comment]
Can we run it twice a day?

**Comment by kunatastic** [comment]
Yeah!! we can do that we will be even better

**Review by bodhish — APPROVED** [review]

**Comment by bodhish** [comment]
I thought the data loading service handled it. We should fix it.

**Comment by rithviknishad** [comment]
@bodhi nope, the scrapper seems to simply be using start and end date with no time specified. I'll try to fix it ASAP, but need to discuss abt how to remove duplicates in already generated data in today's EOD.

**Pull request merged**
