### PR TITLE
hidden leaderboard filters in mobile view

### LINKED ISSUE #363: Leaderboard filters occupying so much space in mobile view
### Action Items
- [ ] Make the filters collapsible in mobile view or move "Role" and "Sorting" filters to secondary filters inside a popover which can be viewed upon pressing a button.
- [ ] Reduce the font-size in mobile view

image

### PR DESCRIPTION
**Pull request by kshitijv256**
### Changes

- fixes #363 
- made filters collapsible in mobile view

### Screenshots
Screenshot from 2024-03-14 22-40-32
Screenshot from 2024-03-14 22-40-41

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Can we instead use a Filter Icon Button to show/hide the filters?

**Comment by kshitijv256** [comment]
@rithviknishad Is this fine?

Screenshot from 2024-03-29 23-14-32

Screenshot from 2024-03-29 23-14-39

**Comment by bodhish** [comment]
@kshitijv256 The design looks good; Lets ship it out

**Comment by kshitijv256** [comment]
@bodhish I have already added this change in preivious commit [9fbcd78](https://github.com/coronasafe/leaderboard/pull/387/commits/9fbcd78dbdd0e5cddf0c5afed410f3850a80bd7d)

**Comment by rithviknishad** [comment]
@kshitijv256 could you resolve the merge conflicts?

**Comment by kshitijv256** [comment]
@rithviknishad fixed conflict

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
