### PR TITLE
Added strings to env file

### PR DESCRIPTION
**Pull request by skks1212**
- Converted all customizable strings to env variables

### CODE REVIEW

**Review by bodhish — CHANGES_REQUESTED** [review]
Add documentation for the keys

**Review by bodhish — APPROVED** [review]
LGTM

**Comment by bodhish** [comment]
@skks1212 you may have to move documentation for the env file into readme. 😅

**Comment by bodhish** [comment]
The quotes look odd 🧐
IMG_7739

**Comment by skks1212** [comment]
@bodhish fixed, looks like Vercel has a strict .env parser 😬. Shifting documentation to readme...

**Review by gigincg — APPROVED** [review]

**Pull request merged**
