### PR TITLE
Fix: showing wrong year in activity

### LINKED ISSUE #50: Showing wrong year in profile
In profile page of leaderboard, it is showing 2021 instead of 2022 in contributions chart!  

image

### PR DESCRIPTION
**Pull request by GokulramGHV**
Fixes #50 

Now the activity section in the user profile page will show the current year. 
 
Before:
image

After:
image

### CODE REVIEW

**Comment by bodhish** [comment]
@GokulramGHV I missed out on this. We should have a similar setup just like GitHub

By default, it shows last 365 days 
image


 Picking a year would show the details of that year. 
 
image

**Comment by GokulramGHV** [comment]
- Added Github like activity calender (shows activity for the past 5 years and by defaut shows the activity of current year).
- Changed the styling of the activity calender to match the overall dark theme of the site.
- Added funcitonality to view activity on a particular day.

@bodhish Is this okay?

https://user-images.githubusercontent.com/40627011/174432495-e9a8a8ea-4ced-4b73-891f-5f6827c2ab56.mp4

**Comment by bodhish** [comment]
@GokulramGHV nice work. 

Few suggestions.
- by default show last 365 days
- The number of years should be dynamic, you could easily do that by updating the current 5 year function. 
- move the years to the right side just like github

**Comment by GokulramGHV** [comment]
@bodhish I've made the changes.. Is this okay?

https://user-images.githubusercontent.com/40627011/174488550-8c050203-b0c4-4678-8e80-88a1b998f982.mp4

**Comment by bodhish** [comment]
Looks good,the number of years on the right should consider the 1st contribution year to compute the available years.

**Comment by GokulramGHV** [comment]
@bodhish I've added the logic for calculating the no. of years

**Comment by GokulramGHV** [comment]
@bodhish Is this okay?
image

**Comment by bodhish** [comment]
Looks good. @gigincg can you review and merge?

**Pull request merged**
