### PR TITLE
Fix: Bottom Border of Navbar is not sticky

### PR DESCRIPTION
**Pull request by Ashutosh0602**
Previous bottom border of Navbar is not sticky now it is sticky to the position.

close: #319 

Initial:
Screenshot 2024-03-07 at 2 08 07 PM

After sliding slightly:
Screenshot 2024-03-07 at 2 08 27 PM

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
The navbar should be full-width. Only the contents of the navbar should be having a max-width constraint

image

**Comment by Ashutosh0602** [comment]
@rithviknishad fixed the fullscreen navbar border.
Screenshot 2024-03-07 at 4 27 29 PM

**Comment by Ashutosh0602** [comment]
@rithviknishad Please check if it is correct or not?

**Review by rithviknishad — APPROVED** [review]

**Comment by rithviknishad** [comment]
Awesome, LGTM

**Pull request merged**
