### PR TITLE
Configurable secondary color 

### LINKED ISSUE #303: Configurable secondary color
### Problem Statement
Currently, the secondary color is not configurable in the leaderboard.

### Tasks

- [ ] Add CSS Variables for a configurable secondary color to the `theme.css` (in the data repo https://github.com/coronasafe/leaderboard-data/blob/main/config/theme.css)
- [ ] The secondary color for gray in the data repo should be Tailwind's gray color
- [ ] Update tailwind config to extend to have a secondary color palette that uses the newly defined CSS variables
- [ ] Replace all usages of tailwind's gray color such as `bg-gray-***`, `text-gray-***`, `border-gray-***`, etc. with `bg-secondary-***`, etc.

### PR DESCRIPTION
**Pull request by HARSHDOIPHODE**
fixes  #303

### CODE REVIEW

**Comment by HARSHDOIPHODE** [comment]
@rithviknishad please check this PR

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@HARSHDOIPHODE 

1. Give a meaningful title for the PR that conveys what this PR does

2. Link issues in the PR using closing keywords. Refer: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Are you sure you've changed all usages of tailwind's gray?

image

**Comment by HARSHDOIPHODE** [comment]
@rithviknishad  its okay now

**Pull request merged**
