### PR TITLE
Updated script to skip cloning if already cloned

### PR DESCRIPTION
**Pull request by UdaySagar-Git**
fixes - #334 

- Renamed remote name from origin to upsteam 
- Updated script to skip cloning if already cloned

### CODE REVIEW

**Comment by UdaySagar-Git** [comment]
@rithviknishad can you please review

**Review by rithviknishad — APPROVED** [review]
Awesome! LGTM

**Comment by sainak** [comment]
Add shebang 
#!/usr/bin/env bash

**Comment by rithviknishad** [comment]
Done https://github.com/coronasafe/leaderboard/commit/c9076d550ed42883396ba6ba4e9ec51a71a4978e

**Pull request merged**
