### PR TITLE
Enhancements to size of filters in Leaderboard page

### LINKED ISSUE #317: Enhancements to size of filters in Leaderboard page
Currently, the size of each filter is not proper.

- [ ] Search filter should occupy 1/3rd of the total width
- [ ] And the rest of the items should be equally spaced (The role filter is taking unequal space)

image

### PR DESCRIPTION
**Pull request by HARSHDOIPHODE**
fixes #317

### CODE REVIEW

**Comment by HARSHDOIPHODE** [comment]
@rithviknishad  please review the changes
image
image

**Comment by HARSHDOIPHODE** [comment]
@rithviknishad please review

**Comment by bodhish** [comment]
@HARSHDOIPHODE 

image

**Comment by rithviknishad** [comment]
@HARSHDOIPHODE could you clear the merge conflicts?

**Comment by rithviknishad** [comment]
Closing due to inactivity and merge conflicts

**Pull request closed without merging**
