### PR TITLE
Fix overflow in home at 1280px

### PR DESCRIPTION
**Pull request by rash-27**
- #239 
after changes
Screenshot 2024-03-05 145756

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by rithviknishad** [comment]
@rash-27 

image

**Comment by rash-27** [comment]
Ok I'll fix

**Comment by rithviknishad** [comment]
image

@rash-27 ensure prettier is configured

image

**Review by rithviknishad — APPROVED** [review]

**Comment by rash-27** [comment]
Okay, just enabled it thank you

**Pull request merged**
