### PR TITLE
make all icons responsive for mobile and dekstop view

### LINKED ISSUE #238: Feed: Event title is not responsive
image

### PR DESCRIPTION
**Pull request by dgparmar14**
# Description
Make all icons responsive on the basis of posibble lengths

Fixes #238 

## Type of change
Change only who's length will be creating ui problem

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Even though there is enough space for time to be shown in same line, it's going to the next line. Let's keep it in a single line if we have the space

image

**Comment by dgparmar14** [comment]
> Even though there is enough space for time to be shown in same line, it's going to the next line. Let's keep it in a single line if we have the space
> 
> image

Yes,There is a space but I do it because time will be shown below for both Mobile and desktop view .In mobile view there is need to in below line because there is no space.So, I do it same change in the desktop.

**Comment by rithviknishad** [comment]
@dgparmar14 We could simply use `inline-flex` to create an inline-flex container that flows with text. This way what needs to go in new line and what not is automatically handled.

Refer: https://tailwindcss.com/docs/display#inline-flex

**Comment by dgparmar14** [comment]
@rithviknishad In mobile view is it better to below line?

**Review by rithviknishad — CHANGES_REQUESTED** [review]
image

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Why is the whole event title wrapped in a link that opens the related repo?

**Comment by rithviknishad** [comment]
Why? shouldn't it open something related to the event?

**Comment by dgparmar14** [comment]
Okay try to fix it

**Comment by dgparmar14** [comment]
> Why? shouldn't it open something related to the event?

I will change it according to the main leader board repo link will be same as per previous?

**Comment by rithviknishad** [comment]
Yup, revert changes to the link. Not in the scope of this issue/PR

**Comment by dgparmar14** [comment]
> Yup, revert changes to the link. Not in the scope of this issue/PR

Responsiveness is done or any changes needed?

**Comment by rithviknishad** [comment]
image

**Comment by dgparmar14** [comment]
@rithviknishad I think now it is done.

**Comment by rithviknishad** [comment]
> image

This issue is still present

**Comment by dgparmar14** [comment]
Okk, Let me clear for clicking link .
It is an already in main repo code. So whenever link on user name it will navigate to the user's profile

> > image
> 
> This issue is still present

In which screen size it occurs because i try all device on chrome for responsive ness and it is working fine

**Comment by dgparmar14** [comment]
> We can make it responsive by simplifying the component event title to be as shown in the example [here](https://tailwindcss.com/docs/display#inline-flex) regardless of what window size it is.

I already use it but there is also need of flex-wrap so i add it also can you please review and there is still not fixed i will do it

**Comment by dgparmar14** [comment]
Yes, there is still issues I will fix it 😅
when I run it on my device and check responsiveness it's work really fine and in deployment 🙂. can you check code

**Comment by dgparmar14** [comment]
@rithviknishad it's now finally done i checked all possible way can you please review if there is still issue then please telll me.

**Comment by rithviknishad** [comment]
Hey @dgparmar14 could you rebase with the latest main branch and do a `pnpm install` and resolve the conflicts?

**Review by rithviknishad — APPROVED** [review]
LGTM, you've made it responsive! Let's merge it as soon as the conflicts are resolved

**Comment by dgparmar14** [comment]
> LGTM, you've made it responsive! Let's merge it as soon as the conflicts are resolved

Sure , I will do it till noon .

**Pull request merged**
