### PR TITLE
Updated symlinks, added scripts, updated readme

### PR DESCRIPTION
**Pull request by skks1212**
- Removed symlinks and incorporated direct paths
- Removed `load-org-data.sh` in favor of `yarn load-data` (handled by node)
- Server wont start before org data has been loaded.
- Readme updated with new Variable.

### CODE REVIEW

**Comment by bodhish** [comment]
@skks1212 let get the deploy working?

**Comment by rithviknishad** [comment]
@skks1212 still same issue. 5 minutes past and still couldn't clone this repo... Did not even reach the install / build step.

image

**Comment by skks1212** [comment]
@bodhish @rithviknishad ready to review

**Review by rithviknishad — APPROVED** [review]
LGTM, let's try merging this.

**Pull request merged**
