### PR TITLE
Update Navbar styling for readability closes #359

### LINKED ISSUE #359: background color of navbar causes issues with readability
In certain cases, when the content behind the navbar has white color, the navbar contents are not readable.

image

### PR DESCRIPTION
**Pull request by rash-27**
- closes #359 
image
Screenshot from 2024-03-11 10-22-24

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
Would it be possible to keep the blur with the `bg-background` as shade color with a higher opacity?

**Comment by rash-27** [comment]
i will try it

**Comment by rash-27** [comment]
image
how does this look ?

**Comment by rithviknishad** [comment]
I think the earlier one itself looked good 😅

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
